<a href="https://colab.research.google.com/github/lalithatv/Machine_Learning_Basics/blob/master/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

**Creating one dimentional matrix**

In [ ]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
print(a.shape)
print(type(a))

(3,)
<class 'numpy.ndarray'>


In [ ]:
b = np.array([1.1,2.2,3.3])
print(b)

[1.1 2.2 3.3]


In [ ]:
print(b.shape)
print(type(b))

(3,)
<class 'numpy.ndarray'>


**To access the elements**

In [ ]:
print(a[0])
print(b[2])

1
3.3


**To print type of elements**

In [ ]:
print(type(a[2]))
print(type(b[1]))

<class 'numpy.int64'>
<class 'numpy.float64'>


**Creating two D Matrix**

In [ ]:
c = np.array([[1,2],[3,4]])
print(c)

[[1 2]
 [3 4]]


In [ ]:
print(c.shape)

(2, 2)


**Ones and zeros**

In [ ]:
d = np.ones((2,2))


In [ ]:
print(d)

[[1. 1.]
 [1. 1.]]


In [ ]:
print(d.shape)
print(type(d))
print(type(d[0][0]))

(2, 2)
<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [ ]:
e = np.zeros((3,3))

In [ ]:
print(e)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
print(e.shape)
print(type(e))
print(type(e[0][0]))

(3, 3)
<class 'numpy.ndarray'>
<class 'numpy.float64'>


**Create Random number matrix**

In [ ]:
f = np.random.random((2,2))

In [ ]:
print(f)

[[0.5108992  0.52894254]
 [0.32296936 0.19543462]]


In [ ]:
print(f.shape)

(2, 2)


**Array Math**

In [ ]:
add = a+b
print("addition")
print(add)
print(np.add(a,b))


addition
[2.1 4.2 6.3]
[2.1 4.2 6.3]


In [ ]:
sub = a-b
print("subtraction")
print(sub)
print(np.subtract(a,b))


subtraction
[-0.1 -0.2 -0.3]
[-0.1 -0.2 -0.3]


In [ ]:
mul = a*b
print("multiplication")
print(mul)
print(np.multiply(a,b))


multiplication
[1.1 4.4 9.9]
[1.1 4.4 9.9]


In [ ]:
div = a/b
print("division")
print(div)
print(np.divide(a,b))


division
[0.90909091 0.90909091 0.90909091]
[0.90909091 0.90909091 0.90909091]


**Array Concat**


In [ ]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

In [ ]:
print(v1)
print(v2)

[1 2 3]
[4 5 6]


In [ ]:
print(v1.shape)
print(v2.shape)

(3,)
(3,)


In [ ]:
concat = np.concatenate( (v1,v2) )

In [ ]:
print(concat)

[1 2 3 4 5 6]


In [ ]:
print(concat.shape)

(6,)


In [ ]:
v3 = np.array([[1,2,3],[4,5,6]])
v4 = np.array([[40,40,40],[50,50,50]])

In [ ]:
print(v3)
print(v4)

[[1 2 3]
 [4 5 6]]
[[40 40 40]
 [50 50 50]]


In [ ]:
print(v3.shape)
print(v4.shape)

(2, 3)
(2, 3)


In [ ]:
concat_0 = np.concatenate( (v3,v4) , axis=0 )
print(concat_0)


[[ 1  2  3]
 [ 4  5  6]
 [40 40 40]
 [50 50 50]]


In [ ]:
concat_1 = np.concatenate( (v3,v4) , axis=1 )
print(concat_1)

[[ 1  2  3 40 40 40]
 [ 4  5  6 50 50 50]]


In [ ]:
v_stack = np.vstack( (v3,v4) )
print(v_stack)

[[ 1  2  3]
 [ 4  5  6]
 [40 40 40]
 [50 50 50]]


In [ ]:
h_stack = np.hstack( (v3,v4) )
print(h_stack)

[[ 1  2  3 40 40 40]
 [ 4  5  6 50 50 50]]


**Expand Dimensions**

In [ ]:
a = np.array([500,200,100])
print(a)

[500 200 100]


In [ ]:
#Insert the new axis along the row
b = np.expand_dims(a,axis=0)
print(b)
print(b.shape)

[[500 200 100]]
(1, 3)


In [ ]:
#Insert the new axis along the column
c = np.expand_dims(a,axis=1)
print(c)
print(c.shape)

[[500]
 [200]
 [100]]
(3, 1)


**Unique**

In [ ]:
m = np.array([1,2,1,1,4])


In [ ]:
#get unique elements and their indexes

In [ ]:
n , indices = np.unique ( m ,return_index=True )
print(n)
print(indices)

[1 2 4]
[0 1 4]
